name: Validate Homey App
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    uses: athombv/athom-github-workflow/.github/workflows/homey-app-validate.yml@master
    secrets: inherit
