name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

# Needed in order to create a release
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create release
        run: gh release create ${{ env.RELEASE_VERSION }} -t ${{ env.RELEASE_VERSION }} --notes "" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
